.templates_sha: &templates_sha 79c325922670137e8f0a4dc5f6f097e0eb57c1af

include:
  - project: 'freedesktop/ci-templates'
    ref: *templates_sha
    file: '/templates/debian.yml'

variables:
  FDO_UPSTREAM_REPO: dbus/zbus

stages:
  - container
  - pages

.debian:
  variables:
    # Update this tag when you want to trigger a rebuild
    FDO_DISTRIBUTION_TAG: '2021-09-25.1'
    # Uncomment if you want to always rebuild the container, useful when hacking on it
    #FDO_FORCE_REBUILD: 1
    FDO_DISTRIBUTION_VERSION: 10
    FDO_DISTRIBUTION_PACKAGES: >-
      git
      wget
      ca-certificates
      build-essential
      libssl-dev
      dbus
      libglib2.0-dev
      pkg-config
      lcov
      python3-pip
      python3-setuptools
    FDO_DISTRIBUTION_EXEC: >-
      gitlab/install-rust.sh stable &&
      pip3 install lcov_cobertura &&
      pip3 install codespell
  before_script:
    - source ./gitlab/env.sh
    - mkdir .cargo && echo -e "[net]\ngit-fetch-with-cli = true" > .cargo/config
    # If cargo exists assume we probably will want to update
    # the lockfile
    - |
      if command -v cargo; then
        cargo generate-lockfile --color=always
        cargo update --color=always
      fi

container:
  extends:
    - .debian
    - .fdo.container-build@debian
  stage: container

.debian_img:
  extends:
    - .debian
    - .fdo.distribution-image@debian

pages:
  image: "hrektts/mdbook"
  stage: pages
  before_script:
    - export PATH="$PATH:$CARGO_HOME/bin"
    - mdbook --version || cargo install --debug mdbook
  script:
    - mkdir -p public/1.0
    - mdbook build book
    - mdbook build book-1.0
    - cp -r ./book/book/* ./public
    - cp -r ./book-1.0/book/* ./public/1.0/
    - find $PWD/public | grep "\.html\$"

  artifacts:
    paths:
      - public

  only:
    refs:
      - tags
    changes:
      - book/**/*
